name: Process Log Entry

on:
  repository_dispatch:
    types: [log_entry]

permissions:
  contents: write

jobs:
  process-log:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install Claude Code CLI
        run: npm install -g @anthropic-ai/claude-code
      
      - name: Process log entry with Claude
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          TZ: America/Chicago
        run: |
          # Get the message from the event payload
          MESSAGE="${{ github.event.client_payload.message }}"
          
          echo "Processing log entry: $MESSAGE"
          echo "Current Central Time: $(date)"
          
          # Use Claude CLI to process the log entry
          # Using echo to pipe the prompt to claude via stdin
          echo "I need you to process this log entry: '$MESSAGE'. 
             
             IMPORTANT: When determining what day it is, use US Central Time (America/Chicago). The current date/time in Central Time is: $(date '+%A, %B %d, %Y at %I:%M %p %Z').
             
             Based on today's date in Central Time, add this entry to the appropriate log file in the logs/ directory.
             The log files are named after Monday's date (e.g., 8-18-2025.md for the week starting Monday, August 18, 2025).
             
             If today's entry already exists in the file, append the new information to it.
             If today's entry doesn't exist yet, create it with the appropriate day header.
             
             Use the same format as existing entries in the log files.
             Just update the log file, don't provide any other output." | claude --print --allowed-tools "Read Write Edit"
      
      - name: Update dashboard using command file
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          TZ: America/Chicago
        run: |
          echo "Updating dashboard with latest data..."
          echo "Current Central Time: $(date)"
          
          # Extract the command content, skipping the YAML frontmatter
          # The frontmatter is between two --- lines, so we skip everything up to and including the second ---
          COMMAND_CONTENT=$(awk '/^---$/{f++;next} f==2{print}' .claude/commands/update-index.md)
          
          # Create the full prompt with timezone context and the command
          FULL_PROMPT="IMPORTANT: When determining what day it is, use US Central Time. The current date/time in Central Time is: $(date '+%A, %B %d, %Y at %I:%M %p %Z').

$COMMAND_CONTENT"
          
          # Send the prompt to Claude
          echo "$FULL_PROMPT" | claude --print --allowed-tools "Read Write Edit"
      
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Add all changes
          git add -A
          
          # Commit with the original message
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update logs and dashboard via chat: ${{ github.event.client_payload.message }}"
            git push origin main
          fi